### ISSUE TITLE
本地无IPv6地址具体该如何设置呢？

### ISSUE THREAD

**Issue by sunlewuyou** [dylanbai8/Onekey_Caddy_PHP7_Sqlite3#15]
如果本地网络不支持IPv6的可以通过cloudflareCDN转换为IP4，不知道该怎么按照作者您这句话操作，能否写出具体的步骤，造福我们广大的小白，您的一键脚本是我用了这么多人中最好最人性化的！深表感谢！！！

**Comment by dylanbai8** [comment]
1.确定你的vps有ipv6地址，知道你vps的ipv6地址是多少，如果有多个的话随便选择一个。有些idc服务商需要在后台手动生成ipv6。
2.修改域名ns，把域名绑定到cloudflareCDN。
3.添加一个 AAAA 记录，记录解析到你vps的ipv6，并开启cdn橙色云朵。

以上搞定之后，执行Onekey_Caddy_PHP7_Sqlite3安装脚本。

**Comment by sunlewuyou** [comment]
谢谢老大回答！明白了！
