### ISSUE TITLE
不能多线程下载？

### ISSUE THREAD

**Issue by cililianjie** [dylanbai8/Onekey_Caddy_PHP7_Sqlite3#17]
你好。我安装的可道云，用IDM下载显示数据冲突，是不是不能多线程下载，请问是什么原因？

**Comment by wenhairu** [comment]
怎么解决的？我上传的种子文件，直链下载后是txt…

**Comment by cililianjie** [comment]
> 
> 
> 怎么解决的？我上传的种子文件，直链下载后是txt…
没解决呀，就找找其他教程了
